set(CPACK_PACKAGE_NAME log4cplus)
set(CPACK_PACKAGE_VERSION "${log4cplus_version_major}.${log4cplus_version_minor}.${log4cplus_version_patch}")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "log4cplus is a log4j-inspired logging library for C++")
set(CPACK_RESOURCE_FILE_LICENSE ${log4cplus_SOURCE_DIR}/LICENSE)
set(CPACK_PACKAGE_DESCRIPTION_FILE ${log4cplus_SOURCE_DIR}/README.md)
include(CPack)
