[= AutoGen5 template -*- Mode: scheme -*-
am
=][=
(use-modules (ice-9 ftw))
=]## Generated by Autogen from [= (tpl-file) =]

TESTSUITE = %D%/testsuite
AUTOTEST = $(AUTOM4TE) --language=Autotest
TESTSUITE_AT = \
[=
(emit "\t"
      (join " \\\n\t"
            (map (lambda (x) (string-append "%D%/" x))
                 (scandir "."
                          (lambda (x) (string-suffix-ci? ".at" x)))))
      "\n")
=]

all: $(TESTSUITE)

$(TESTSUITE): $(TESTSUITE_AT) %D%/atlocal.in
	cd "$(abs_top_srcdir)" && $(AUTOTEST) -I tests %D%/testsuite.at -o $@

%D%/atconfig: $(top_builddir)/config.status
	cd "$(top_builddir)" && ./config.status $@

check-local: %D%/atconfig %D%/atlocal $(TESTSUITE)
	cd "$(top_builddir)/tests" && $(SHELL) $(abs_top_srcdir)/$(TESTSUITE) $(TESTSUITEFLAGS)

clean-local:
	cd "$(top_builddir)/tests" && (test ! -f '$(abs_top_srcdir)/$(TESTSUITE)' || $(SHELL) '$(abs_top_srcdir)/$(TESTSUITE)' --clean)

EXTRA_DIST += %D%/testsuite.at $(TESTSUITE) %D%/atlocal.in
[= FOR tests =][=
 (out-push-new (string-append (get "name") "/" "Makefile.am"))
=]## Generated by Autogen from [= (tpl-file) =]

[= IF need_threads =]if MULTI_THREADED
[= ENDIF =]noinst_PROGRAMS += [=name=]

[=name=]_sources = \
[=
(emit "\t"
      (join " \\\n\t"
            (map (lambda (x) (string-append "%D%/" x))
                 (scandir (get "name")
                          (lambda (x)
                            (or
                             (string-suffix-ci? ".cxx" x))))))
      "\n")
=]
[=name=]_SOURCES = $([=name=]_sources)

[=name=]_LDADD = $(liblog4cplus_la_file)
[=name=]_LDFLAGS = -no-install

if BUILD_WITH_WCHAR_T_SUPPORT
noinst_PROGRAMS += [=name=]U
[=name=]U_CPPFLAGS = $(AM_CPPFLAGS) -DUNICODE=1
[=name=]U_SOURCES = $([=name=]_sources)
[=name=]U_LDADD = $(liblog4cplusU_la_file)
[=name=]U_LDFLAGS = -no-install
endif
[= IF need_threads =]
endif
[= ENDIF =][=
 (out-pop)
=][= ENDFOR test =]
